/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bcu_userlab_haptics_HDAL_HDAL */

#ifndef _Included_com_bcu_userlab_haptics_HDAL_HDAL
#define _Included_com_bcu_userlab_haptics_HDAL_HDAL
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDAL_ISREADY
#define com_bcu_userlab_haptics_HDAL_HDAL_HDAL_ISREADY 0L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDAL_NOT_CALIBRATED
#define com_bcu_userlab_haptics_HDAL_HDAL_HDAL_NOT_CALIBRATED 4L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDAL_SERVO_NOT_STARTED
#define com_bcu_userlab_haptics_HDAL_HDAL_HDAL_SERVO_NOT_STARTED 2L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDAL_UNINITIALIZED
#define com_bcu_userlab_haptics_HDAL_HDAL_HDAL_UNINITIALIZED 1L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_1
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_1 1L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_2
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_2 2L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_3
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_3 4L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_4
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_4 8L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_ANY
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_BUTTON_ANY -1L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEFAULT_DEVICE_ID
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEFAULT_DEVICE_ID 0L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INVALID_HANDLE
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INVALID_HANDLE -1L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_SERVOOP_CONTINURE
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_SERVOOP_CONTINURE 1L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_SERVOOP_EXIT
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_SERVOOP_EXIT 0L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_HDAL
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_HDAL 17L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE 33L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE_SDK
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE_SDK 34L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE_COMMS
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE_COMMS 35L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE_OS
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_DEVICE_OS 36L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_GRIP
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_GRIP 51L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_ERROR_INIT_FAILED
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_ERROR_INIT_FAILED 16L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_ERROR_INTERNAL
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_ERROR_INTERNAL 2L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_ERROR_STACK_OVERFLOW
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_ERROR_STACK_OVERFLOW 1L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DEVICE_ALREADY_INITED
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DEVICE_ALREADY_INITED 22L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DEVICE_FAILURE
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DEVICE_FAILURE 21L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DEVICE_NOT_CONNECTED
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DEVICE_NOT_CONNECTED 23L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DLL_LOAD_ERROR
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_DLL_LOAD_ERROR 20L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_ERROR_MASK
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_ERROR_MASK 31L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_INI_DLL_STRING_NOT_FOUND
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_INI_DLL_STRING_NOT_FOUND 18L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_INI_MANUFACTURER_NAME_STRING_NOT_FOUND
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_INI_MANUFACTURER_NAME_STRING_NOT_FOUND 19L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_INI_NOT_FOUND
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_INIT_INI_NOT_FOUND 17L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_NO_ERROR
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_NO_ERROR 0L
#undef com_bcu_userlab_haptics_HDAL_HDAL_HDL_SERVO_START_ERROR
#define com_bcu_userlab_haptics_HDAL_HDAL_HDL_SERVO_START_ERROR 24L
/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlCountDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlCountDevices
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlCreateServoOp
 * Signature: (Lcom/bcu/userlab/haptics/HDAL/HDLCallback;[Ljava/lang/Object;Z)I
 */
JNIEXPORT jint JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlCreateServoOp
  (JNIEnv *, jclass, jobject, jobjectArray, jboolean);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlDestroyServoOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlDestroyServoOp
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlDeviceModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlDeviceModel
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlDeviceWorkspace
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlDeviceWorkspace
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlGetState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlGetState
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlGetVersion
 * Signature: (I)Lcom/bcu/userlab/haptics/HDAL/HDLVersionInfo;
 */
JNIEXPORT jobject JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlGetVersion
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlInitDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlInitDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlInitIndexedDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlInitIndexedDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlInitNamedDevice
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlInitNamedDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlMakeCurrent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlMakeCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlSetToolForce
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlSetToolForce
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlStart
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlStop
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlToolButton
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlToolButton
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlToolButtons
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlToolButtons
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlToolPosition
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlToolPosition
  (JNIEnv *, jclass);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDAL
 * Method:    hdlUninitDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_bcu_userlab_haptics_HDAL_HDAL_hdlUninitDevice
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
