/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bcu_userlab_haptics_HDAL_HDLU */

#ifndef _Included_com_bcu_userlab_haptics_HDAL_HDLU
#define _Included_com_bcu_userlab_haptics_HDAL_HDLU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDLU
 * Method:    hdluGenerateHapticToAppWorkspaceTransform
 * Signature: ([D[DZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_bcu_userlab_haptics_HDAL_HDLU_hdluGenerateHapticToAppWorkspaceTransform
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jboolean);

/*
 * Class:     com_bcu_userlab_haptics_HDAL_HDLU
 * Method:    hdluGetSystemTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_bcu_userlab_haptics_HDAL_HDLU_hdluGetSystemTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
